AWSTemplateFormatVersion: '2010-09-09' 
Description: 'S3 Static file hosting'

Resources:
# S3 Bucket for Static Website
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-static-website-ab'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false

# S3 Bucket Policy
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
